# Generated by Django 6.0.6 on 2026-06-17 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portaluser',
            name='temp_password',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
